#INITIAL SETTINGS
random_seed             : 42

#Training parameters
epochs                  : 30
batch_size              : 256
patience                : ~
prefetch                : 8
gpu_used                : ['GPU:0', 'GPU:1', 'GPU:2', 'GPU:3']

head_lr                 : 0.5
encoder_lr              : 0.5
use_class_weight        : False

root_save_dir           : 'trained_models/classifiers'

#Model parameters
model_type              : 'supervised'  # One of ['cifar', 'resnet50', 'vae']

projector_dim           : 2048  # For resnet encoder
latent_dim              : 64    # For vae encoder
encoder_weights_path    : None

#Dataset parameters
image_shape             : [224, 224, 3]
train_split             : 0.1
validation_split        : 0.15
dataset_type            : 'tissue_6_0.3'

# Assigned in script
steps                   : ~
num_classes             : ~
